In [1]:
import pandas as pd
import numpy as np
import folium
import random
import os

os.makedirs("visualization", exist_ok=True)
pd.set_option("display.max_colwidth", None)   # 不截断单元格内容
pd.set_option("display.max_columns", None)    # 显示所有列
pd.set_option("display.width", 200)           # 调整行宽

In [2]:
worldtrace = pd.read_pickle('./data/worldtrace_sample.pkl')

In [3]:
worldtrace.head(1)

,time,trajectory
0,"0 2023-01-10 02:16:18 1 2023-01-10 02:16:19 2 2023-01-10 02:16:20 3 2023-01-10 02:16:21 4 2023-01-10 02:16:22 ... 596 2023-01-10 02:26:14 597 2023-01-10 02:26:15 598 2023-01-10 02:26:16 599 2023-01-10 02:26:17 600 2023-01-10 02:26:18 Name: time, Length: 601, dtype: datetime64[ns]","[[36.796112, -120.736428], [36.796245, -120.736519], [36.796465, -120.73667], [36.796686, -120.736822], [36.796907, -120.736974], [36.797128, -120.737125], [36.797349, -120.737277], [36.797571, -120.737429], [36.797792, -120.737581], [36.798011, -120.737731], [36.79823, -120.737881], [36.798447, -120.738031], [36.798665, -120.73818], [36.798881, -120.738329], [36.799096, -120.738476], [36.799312, -120.738624], [36.799526, -120.738771], [36.799739, -120.738917], [36.799951, -120.739063], [36.800163, -120.739208], [36.800375, -120.739354], [36.800586, -120.739499], [36.8008, -120.739646], [36.801015, -120.739794], [36.801234, -120.739943], [36.801455, -120.740095], [36.801678, -120.740249], [36.801903, -120.740402], [36.802127, -120.740557], [36.802351, -120.74071], [36.802574, -120.740863], [36.802797, -120.741016], [36.803018, -120.741168], [36.80324, -120.74132], [36.803461, -120.741472], [36.803683, -120.741625], [36.803905, -120.741777], [36.804126, -120.741929], [36.804347, -120.742081], [36.804568, -120.742232], [36.80479, -120.742384], [36.805011, -120.742535], [36.805237, -120.742689], [36.805453, -120.742838], [36.805673, -120.742989], [36.805892, -120.743139], [36.806112, -120.74329], [36.806331, -120.743441], [36.806551, -120.743592], [36.806771, -120.743743], [36.80699, -120.743894], [36.80721, -120.744045], [36.80743, -120.744196], [36.807651, -120.744348], [36.807872, -120.7445], [36.808093, -120.744652], [36.808315, -120.744805], [36.808537, -120.744957], [36.808759, -120.74511], [36.80898, -120.745262], [36.809203, -120.745415], [36.809425, -120.745568], [36.809669, -120.745736], [36.809869, -120.745873], [36.810091, -120.746025], [36.810313, -120.746179], [36.810536, -120.746331], [36.810758, -120.746484], [36.81098, -120.746637], [36.811201, -120.746789], [36.811423, -120.746941], [36.811645, -120.747094], [36.811866, -120.747246], [36.812087, -120.747398], [36.812309, -120.74755], [36.812529, -120.747702], [36.81275, -120.747854], [36.81297, -120.748005], [36.813191, -120.748157], [36.813411, -120.748308], [36.813632, -120.74846], [36.813855, -120.748613], [36.814078, -120.748766], [36.814301, -120.74892], [36.814525, -120.749074], [36.81475, -120.749229], [36.814975, -120.749383], [36.815202, -120.749539], [36.815428, -120.749695], [36.815654, -120.74985], [36.81588, -120.750006], [36.816106, -120.750161], [36.816332, -120.750316], [36.816557, -120.750471], [36.816783, -120.750626], [36.817009, -120.750781], [36.817234, -120.750936], [36.81746, -120.751091], [36.817686, -120.751247], [36.817912, -120.751402], ...]"

In [19]:
test = pd.read_pickle('~/UniTraj/data/shards/test2.pkl')

In [22]:
test.head(3)

,time,trajectory
0,"0 2023-09-07 07:48:56 1 2023-09-07 07:48:57 2 2023-09-07 07:48:58 3 2023-09-07 07:48:59 4 2023-09-07 07:49:00 ... 156 2023-09-07 07:51:32 157 2023-09-07 07:51:33 158 2023-09-07 07:51:34 159 2023-09-07 07:51:35 160 2023-09-07 07:51:36 Name: time, Length: 161, dtype: datetime64[ns]","[[24.1974, 120.518598], [24.1974, 120.518598], [24.1973995, 120.5185985], [24.197399, 120.518599], [24.197399, 120.518599], [24.197399, 120.5186], [24.197399, 120.5186], [24.197399, 120.518602], [24.197398, 120.518607], [24.197395, 120.518618], [24.197391, 120.518639], [24.197383, 120.518677], [24.197372, 120.518733], [24.197357, 120.518804], [24.197338, 120.518898], [24.197318, 120.518988], [24.197294, 120.519098], [24.197268, 120.519219], [24.19724, 120.519348], [24.197211, 120.519482], [24.197182, 120.519616], [24.197153, 120.519751], [24.197124, 120.519886], [24.197095, 120.520022], [24.197065, 120.520159], [24.197035, 120.520296], [24.197006, 120.520433], [24.196976, 120.52057], [24.196947, 120.520706], [24.196917, 120.520842], [24.196886, 120.520977], [24.196854, 120.521115], [24.19682, 120.521255], [24.196787, 120.521396], [24.196753, 120.521537], [24.19672, 120.521677], [24.196687, 120.521816], [24.196654, 120.521955], [24.196621, 120.522092], [24.196588, 120.52223], [24.196556, 120.522365], [24.196521, 120.522512], [24.196493, 120.522631], [24.196461, 120.522764], [24.196427, 120.52291], [24.196399, 120.523034], [24.196369, 120.523171], [24.196339, 120.523309], [24.196308, 120.52345], [24.196277, 120.523592], [24.196246, 120.523733], [24.196215, 120.523875], [24.196184, 120.524017], [24.196153, 120.524159], [24.196122, 120.5243], [24.196091, 120.524441], [24.19606, 120.52458], [24.19603, 120.52472], [24.195999, 120.524862], [24.195968, 120.525003], [24.195937, 120.525147], [24.195906, 120.525291], [24.195875, 120.525435], [24.195844, 120.525577], [24.195814, 120.525719], [24.195783, 120.525861], [24.195753, 120.526003], [24.195722, 120.526144], [24.195692, 120.526284], [24.195662, 120.526424], [24.195633, 120.526559], [24.195604, 120.526693], [24.195575, 120.526828], [24.195545, 120.526962], [24.195516, 120.527098], [24.195486, 120.527235], [24.195455, 120.527372], [24.195425, 120.527511], [24.195395, 120.527646], [24.195366, 120.527781], [24.195337, 120.527912], [24.195309, 120.528038], [24.195282, 120.528162], [24.195255, 120.528284], [24.195228, 120.528407], [24.195201, 120.528532], [24.195173, 120.528656], [24.195146, 120.52878], [24.195119, 120.528902], [24.195092, 120.529024], [24.195064, 120.529145], [24.195037, 120.529263], [24.195011, 120.529379], [24.194986, 120.529491], [24.194961, 120.5296], [24.194937, 120.529705], [24.194915, 120.529804], [24.194893, 120.529899], [24.194875, 120.529982], [24.194858, 120.530055], ...]"

In [21]:
test.size

2

In [4]:
worldtrace.size

4000

In [5]:
# random select 16 trajectories from worldtrace and draw it
worldtrace_sample = worldtrace.sample(100)
trajectory = worldtrace_sample['trajectory']
trajectory = trajectory.apply(lambda x: np.array(x))
trajectory = trajectory.values

m = folium.Map(location=trajectory[0][0], zoom_start=13)
for i in range(len(trajectory)):
    folium.Marker(list(trajectory[i][0])).add_to(m)
    color = '#' + ''.join([random.choice('0123456789ABCDEF') for j in range(6)])
    folium.PolyLine(trajectory[i], color = color,weight=10).add_to(m)

m.save('./visualization/sample.html')
m